apiVersion: v1
kind: Service
metadata:
  name: nodes
  namespace: hpc-nico
spec:
  selector:
    net: headless
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hpc-node
  namespace: hpc-nico
  labels:
     name: hpc-node
spec:
  selector:
    matchLabels:
      app: openpbs-node
  serviceName: "nodes"
  replicas: 2
  template:
    metadata:
      labels:
        app: openpbs-node
        net: headless
        role: compute-node
        partition: COMPUTE
    spec:
      initContainers:
      - name: openpbs-init
        image: nyk0/openpbsinit
        command: ["/usr/local/bin/python"]
        args: ["generate_pbs_conf.py"]
        volumeMounts:
        - mountPath: /pbsconf
          name: pbsconf
      containers:
      - name: openpbs-node
        image: nyk0/openpbs
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
        volumeMounts:
        - mountPath: /pbsconf
          name: pbsconf
        - mountPath: /home
          name: home
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: pbsconf
        emptyDir: {}
      - name: home
        persistentVolumeClaim:
          claimName: pvc-nfs-home
      dnsConfig:
        searches:
          - nodes.hpc-nico.svc.cluster.local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: control-node
  namespace: hpc-nico
  labels:
     name: control-node
spec:
  selector:
    matchLabels:
      app: openpbs-server
  serviceName: "nodes"
  replicas: 1
  template:
    metadata:
      labels:
        app: openpbs-server
        role: control-node
        net: headless
    spec:
      initContainers:
      - name: openpbs-init
        image: nyk0/openpbsinit
        command: ["/usr/local/bin/python"]
        args: ["generate_pbs_conf.py"]
        volumeMounts:
        - mountPath: /pbsconf
          name: pbsconf
      containers:
      - name: openpbs-server
        image: nyk0/openpbs
        command: ["/bin/bash"]
        args: ["start-pbs.sh"]
        volumeMounts:
        - mountPath: /pbsconf
          name: pbsconf
        - mountPath: /home
          name: home
      - name: openpbs-conf
        image: nyk0/openpbsconf
        command: ["/usr/local/bin/python"]
        args: ["generate_pbs_conf.py"]
        volumeMounts:
        - mountPath: /pbsconf
          name: pbsconf
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: pbsconf
        emptyDir: {}
      - name: home
        persistentVolumeClaim:
          claimName: pvc-nfs-home
      dnsConfig:
        searches:
          - nodes.hpc-nico.svc.cluster.local
