---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-hpc-nico
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-hpc-nico
subjects:
- kind: ServiceAccount
  name: default
  namespace: hpc-nico
roleRef:
  kind: ClusterRole
  name: pods-list-hpc-nico
  apiGroup: rbac.authorization.k8s.io
