apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-home
  namespace: hpc-nico
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/home
    server: admin.lab.local
