apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-home
  namespace: hpc-nico
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
